server:
  port: 0
spring:
  application:
    name: summer-cloud-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.199:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: summer
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connect-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka  #,http://127.0.0.1:9999/eureka
    #设置客户端信息的上报时间
    instance-info-replication-interval-seconds: 10
    #获取注册信息的周期时间
    registry-fetch-interval-seconds: 10
    #enabled: false
  instance:
    instance-id: ${spring.application.name}1
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认30s)
    #lease-expiration-duration-in-seconds: 1
    #Eureka服务端在收到最后一次心跳等待的上限时间,单位为秒(默认90s),超时将剔除服务
    #lease-renewal-interval-in-seconds: 2
# mybatis配置内容
mybatis:
  #mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.summer.payment.repository.entity
  #config-location: classpath:config/mybatis-config.xml
# mapper配置内容
mapper:
  mappers: # 设置基础 Mapper 接口
  not-empty: true #在insert和update操作时,是否会判断字段是否为空
  identity: MYSQL
# PageHelper 配置内容
pagehelper:
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
  # 你可以配置helperDialect属性来指定分页插件使用哪种方言。
  helper-dialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  # pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false，
  # 分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，
  # 查找到合适的值时就会自动分页。 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。
  support-methods-arguments: true
#配置日志级别
logging:
  level:
    com:
      summer:
        payment:
          repository:
            mapper: debug
