server:
  port: 8011
spring:
  application:
    name: summer-cloud-service-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
#暴露要监控的服务信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: false
